version: "3"
services:
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARG=--encoding=UTF-8
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
