# Generated by Django 4.1 on 2022-12-12 18:00

from django.db import migrations, models
import django.utils.timezone
import record.utils.time_utils
import record.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "tag",
                    models.CharField(
                        default="IN",
                        max_length=10,
                        validators=[record.validators.validate_tag],
                    ),
                ),
                ("check_time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "date",
                    models.DateField(default=record.utils.time_utils.working_timezone),
                ),
                ("go_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("leave_time", models.DateTimeField(null=True)),
                ("working_time", models.IntegerField(default=0)),
                ("break_time", models.IntegerField(default=0)),
            ],
        ),
    ]
