# Generated by Django 4.1.3 on 2022-12-04 17:08

from django.db import migrations, models
import django.utils.timezone
import record.utils.time_utils


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrecord",
            name="check_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="date",
            field=models.DateField(default=record.utils.time_utils.working_timezone),
        ),
    ]
