# Generated by Django 4.1.3 on 2022-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0003_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrecord",
            name="user_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
